// <auto-generated />
namespace Vendas.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class properties_not_required_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(properties_not_required_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202310191159386_properties_not_required_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
