// <auto-generated />
namespace Vendas.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Change_field_Optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_field_Optional));
        
        string IMigrationMetadata.Id
        {
            get { return "202311271821472_Change_field_Optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
