// <auto-generated />
namespace Vendas.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_state_Address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_state_Address));
        
        string IMigrationMetadata.Id
        {
            get { return "202311061234507_add_state_Address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
