// <auto-generated />
namespace Vendas.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Address_User_Mappings_Modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address_User_Mappings_Modified));
        
        string IMigrationMetadata.Id
        {
            get { return "202310021452175_Address_User_Mappings_Modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
