// <auto-generated />
namespace Vendas.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adjust_user_typeUser_optionals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjust_user_typeUser_optionals));
        
        string IMigrationMetadata.Id
        {
            get { return "202311201403036_adjust_user_typeUser_optionals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
