// <auto-generated />
namespace Vendas.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class table_sales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_sales));
        
        string IMigrationMetadata.Id
        {
            get { return "202310061748367_table_sales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
